theme: jekyll-theme-slate

title: PEILIMPACT
#tagline: impact van grondwaterpeil op landbouwpraktijk
description: impact van grondwaterpeil op landbouwpraktijk

#plugins: jekyll-seo-tag

#author: Sarah Garré
#  twitter: sarahgarre
#  picture: /figs/sarah.jpg

