theme: jekyll-theme-slate

title: PEILIMPACT
#tagline: impact van grondwaterpeil op landbouwpraktijk
description: Schatting van de impact van peilverhogingen en vernatting op nabijgelegen landbouwgebied in Vlaanderen

show_downloads: [false]

#plugins:
 # - jekyll-seo-tag

#author: Sarah Garré
#  twitter: sarahgarre
#  picture: /figs/sarah.jpg
